[Add] KirinShiKi
typecho-fans/plugins pull request #127
Opened 2021-06-10 12:38 UTC by JeffersonQin

2021-06-11 04:37 UTC, LittleJake reviewed
这个插件是要搭配Handsome主题吗

2021-06-11 04:50 UTC, JeffersonQin commented
> 这个插件是要搭配Handsome主题吗

是的，需要在介绍里面加吗

2021-06-11 04:50 UTC, JeffersonQin commented
以及希望能加入typecho-fans（x

2021-06-19 09:26 UTC, wuxianucw requested changes

2021-06-19 09:26 UTC, wuxianucw commented on KirinShiKi/Plugin.php
> +        function check_update($version)
注意：可能污染作用域。

考虑替代：

```php
$check_update = function($version) { /* ... */ };
$check_update('3.1.1'); // or $check_update(KirinShiKi_Plugin::VERSION) with const VERSION = '3.1.1'
```

2021-06-19 09:26 UTC, wuxianucw commented on KirinShiKi/Plugin.php
> +        $pjax = new Typecho_Widget_Helper_Form_Element_Radio(
（Optional, just a suggestion）考虑直接获取当前主题设置？或增加“自动适配主题设置”选项？

2021-06-19 09:26 UTC, wuxianucw commented on KirinShiKi/Plugin.php
> +	$code = 'setHref(getHref());';
不要混用空格和 tab

2021-06-19 10:31 UTC, LittleJake commented on KirinShiKi/Plugin.php
> +        function check_update($version)
php应该不存在污染作用域一说吧

2021-06-19 10:34 UTC, wuxianucw commented on KirinShiKi/Plugin.php
> +        function check_update($version)
```php
class A {
    public static function foo() {
        function bar() { echo 'bar'; }
        bar();
    }
}
A::foo(); // 'bar'
bar(); // 'bar'
A::foo(); // Fatal error
```

内部 function 将被提升至 global 作用域，可能造成冲突。

2021-06-19 10:40 UTC, wuxianucw commented on KirinShiKi/Plugin.php
> +        function check_update($version)
如果别的地方同时也定义过 `function check_version(...)`，这里会直接 Fatal error。

2021-06-19 13:18 UTC, JeffersonQin commented on KirinShiKi/Plugin.php
> +        function check_update($version)
ok 这个我去改一下

2021-06-19 13:19 UTC, JeffersonQin commented on KirinShiKi/Plugin.php
> +        $pjax = new Typecho_Widget_Helper_Form_Element_Radio(
这个我个人认为还是交给用户吧（感谢提醒

2021-06-20 01:23 UTC, wuxianucw requested changes

2021-06-20 01:23 UTC, wuxianucw commented on KirinShiKi/js/kirin.js
> -    (function() {
啊这，`Plugin.php` 中调整一致就行了吧，这个 JS 没必要再把空格全换了……

而且 JS 之类的前端 assets 最好还是 minify 一下。

2021-06-20 02:16 UTC, wuxianucw approved these changes

2021-06-20 02:17 UTC, merged